server:
  port: 9192

Spring:
  datasource:
    username: root
    password: Npttzt@12
    url: jdbc:mysql://localhost:3306/hillSideHeaven_hotel_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB
  security:
    user:
      name: admin
      password: admin


